#pragma once

static const char *CONFIG_PORTAL_PAGE_HEAD =
    "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>ESP32 Gateway Setup</title>"
    "<style>"
    ":root{color-scheme:dark;--bg:#080d13;--panel:#101820;--panel2:#151f29;--text:#e8edf2;--muted:#91a1b2;"
    "--line:#263544;--field:#0b1219;--blue:#2f9bff;--blue2:#1979d2;--red:#e05243;"
    "--green:#30c48d;--shadow:0 18px 44px rgba(0,0,0,.34)}"
    "*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#07111d 0,#0b1118 45%,#080d13 100%);"
    "color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif}"
    "body:before{content:\"\";position:fixed;inset:0;pointer-events:none;background:linear-gradient(90deg,rgba(47,155,255,.08),transparent 34%,rgba(48,196,141,.06))}"
    "main{position:relative;width:min(980px,100%);margin:0 auto;padding:24px 16px 34px}"
    ".top{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:18px 0 20px}"
    ".brand{display:flex;gap:12px;align-items:center}.mark{width:42px;height:42px;border-radius:10px;"
    "background:linear-gradient(135deg,#2f9bff,#30c48d);display:grid;place-items:center;color:#061019;font-weight:900;font-size:18px;"
    "box-shadow:0 10px 28px rgba(47,155,255,.28)}"
    "h1{font-size:25px;line-height:1.15;margin:0}p{margin:0}.sub{color:var(--muted);font-size:14px;margin-top:5px}"
    ".status{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.pill{border:1px solid #304253;"
    "background:rgba(16,24,32,.78);border-radius:999px;padding:7px 10px;font-size:12px;font-weight:800;color:#c8d4df}"
    ".grid{display:grid;grid-template-columns:1.25fr .75fr;gap:16px;align-items:start}"
    ".panel{background:rgba(16,24,32,.96);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow);overflow:hidden}"
    ".panel+.panel{margin-top:16px}.panel-head{padding:16px 18px;border-bottom:1px solid var(--line);"
    "display:flex;align-items:center;justify-content:space-between;gap:10px;background:var(--panel2)}"
    "h2{font-size:15px;margin:0}.hint{color:var(--muted);font-size:12px;line-height:1.45}"
    ".panel-body{padding:18px}.row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{margin-bottom:14px}"
    "label{display:flex;align-items:center;justify-content:space-between;gap:10px;font-size:13px;font-weight:800;margin:0 0 6px;color:#dce6ef}"
    "input{width:100%;min-height:42px;border:1px solid #334657;border-radius:7px;background:var(--field);"
    "color:var(--text);font-size:15px;padding:10px 11px;outline:none}"
    "input::placeholder{color:#68798a}input:focus{border-color:var(--blue);box-shadow:0 0 0 3px rgba(47,155,255,.18);background:#0d1721}"
    ".help{color:var(--muted);font-size:12px;margin-top:5px;line-height:1.35}.switch{display:flex;align-items:center;"
    "justify-content:space-between;gap:12px;border:1px solid var(--line);border-radius:7px;background:var(--field);padding:10px 11px;min-height:42px}"
    ".switch input{width:22px;min-height:22px;accent-color:var(--green)}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:4px}"
    "button{border:0;border-radius:7px;background:var(--blue);color:#061019;font-weight:900;font-size:14px;"
    "min-height:42px;padding:10px 14px;cursor:pointer}button:hover{background:#6bb8ff}button.secondary{background:#263544;color:#e8edf2;border:1px solid #3a5065}"
    "button.secondary:hover{background:#31465a}button.danger{background:var(--red);color:#fff}button.danger:hover{background:#f06a5e}"
    "button:disabled{opacity:.62;cursor:wait}.file{border:1px dashed #486174;border-radius:8px;padding:14px;background:#0b1219}.file input{background:#0e1822}"
    ".statusbox{min-height:48px;white-space:pre-wrap;background:#08121a;border:1px solid #24394c;color:#b9ffde;padding:11px;border-radius:7px;"
    "font:13px/1.45 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;margin-top:12px}"
    ".danger-zone{border-color:#66332f}.danger-zone .panel-head{background:#241516}.small{font-size:12px;color:var(--muted)}"
    "@media(max-width:820px){.grid{grid-template-columns:1fr}.top{display:block}.status{justify-content:flex-start;margin-top:14px}}"
    "@media(max-width:560px){main{padding:18px 12px 28px}.row{grid-template-columns:1fr}.panel-body{padding:15px}"
    ".panel-head{display:block}.hint{margin-top:5px}.actions button{width:100%}}"
    "</style></head><body><main>";

static const char *CONFIG_PORTAL_PAGE_TAIL =
    "<script>"
    "const fw=document.getElementById('fw'),ota=document.getElementById('ota'),statusBox=document.getElementById('status');"
    "ota.onclick=async()=>{const f=fw.files[0];if(!f){statusBox.textContent='Choose a firmware .bin file first.';return;}"
    "ota.disabled=true;statusBox.textContent='Uploading '+f.name+'...';"
    "try{const r=await fetch('/ota',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f});"
    "statusBox.textContent=await r.text();}catch(e){statusBox.textContent='Upload failed: '+e.message;}"
    "finally{ota.disabled=false;}};"
    "</script></main></body></html>";
